### ISSUE TITLE
Is it possible to use open source llm's like llama2 ?

### ISSUE THREAD

**Issue by neves8232** [GregorD1A1/TinderGPT#1]

**Comment by GregorD1A1** [comment]
Hey,

For now application uses openai only, but I don't see any problem to add here support for open-source models, for example through ollama. Maybe uncensored models will provide even better output, as outputs of GPT very often too polite and too "chatgpt-stylish".

Althrough there could be potential problems with open source models:
- Non-english languages. As GPT-4 is good on many languages, it's easy to change it, just providing one 'language' variable to the prompt. Open-sourse LLMs usually not able to write smoothly in non-english language until they were specially trained for that concrete language.
- Continuous run on Raspberry. Purpose of the project is to run TinderGPT on private Raspberry Pi to make user not to start application every day, few times a day manually (that's a purpose of automation). That's a problem, because local models will not be able to run on Raspberry, especially while some part of it's RAM (around 3 GB) used by browser. Athrough external API with open-source models could be a solution.

So there are pros and cons of using open-source LLMs. If you want, you can add option to switch from openai to Ollama - to leave gpt as default, with ability to swith to own llm.

**Comment by neves8232** [comment]
That's true, using non english language might not be very good on open source llm's. To use on raspberry pi I was thinking on using hosting providers like together.ai that allow to use the latest ollama for a very cheap price

**Comment by GregorD1A1** [comment]
Together.ai provide possibility to pay per request as I understand (not per server hour)? If yes, why not. Replicate.com also seems to be solution.

If you want, you can test if open-source models will generate reasonable responses, or at least be useful for intermediate steps of response generation (as Analyzer or Commander modules), and if yes, you are welcome to create a PR with support for this models.

**Comment by neves8232** [comment]
I didn't knew replicate.com but if it offers pay per request yeah, that's what together.ai offers also.
Currently working on other projects but I believe it would be an easy integration, either way like I've mentioned it's a great project. Keep it up mate!
