### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by neves8232** [GregorD1A1/TinderGPT#2]
When using the start_tnd returns 

```
"  File "/home/lem/.local/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/home/lem/.local/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/lem/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/lem/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/lem/Desktop/TinderGPT/main.py", line 33, in load_main_page_tnd
    dating_connector.load_main_page()
  File "/home/lem/Desktop/TinderGPT/driver/connectors/tnd_conn.py", line 52, in load_main_page
    if self.driver.find_element('xpath', self.close_tnd_gold_enforser_xpath):
  File "/home/lem/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 831, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "/home/lem/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "/home/lem/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: /html[1]/body[1]/div[2]/main[1]/div[1]/div[1]/div[3]/button[2]/span[1]"
```

Also when using /opener goes to the "likes sent" as the first girl, instead of the actual first girl.

**Comment by neves8232** [comment]
Solved the issue by changing :

        if self.driver.find_element('xpath', self.close_tnd_gold_enforser_xpath):
            self.driver.find_element('xpath', self.close_tnd_gold_enforser_xpath).click()
            print('Tinder gold enforcer closed')

To:

        if self.driver.find_elements('xpath', self.close_tnd_gold_enforser_xpath):
            self.driver.find_element('xpath', self.close_tnd_gold_enforser_xpath).click()
            print('Tinder gold enforcer closed')

Since elements returns false and element returns an exception if not found

**Comment by neves8232** [comment]
"Also when using /opener goes to the "likes sent" as the first girl, instead of the actual first girl."

Just change line 118 on "tnd_conn" to def get_bio(self, girl_nr=2):

**Comment by GregorD1A1** [comment]
@neves8232 What about error with tnd gold enforser - nice solution! It was that kind of error, which shows error, but in fact app works normally ;) But now because of your solution, it will not show that fake error any more.

What about opener clicks to "likes sent", you mean it clicking to that first icon that leads to tinder.com/apps/likes-you
![image](https://github.com/GregorD1A1/TinderGPT/assets/50213363/49f4094f-335a-4991-991f-5492b8c07647)
?
If yes, it strange. For me /opener was working good. That icon is girl_nr=0, so when clicking on girl_nr=1, it opens first girl for me.

**Comment by GregorD1A1** [comment]
Well, it's interesting that you had 2 options, maybe you had some paid version of tinder, and that's why it looks different?

Ok, I see your code, It opens all the girls it has. It's interesting approach! I'll think to use some parts of it.

Thanks for appreciation, using the project and improving it!

**Comment by neves8232** [comment]
I was using a free version tho, idk if other people have the same 2 options as me or it's based on location or something🤷.
No problem mate, I love python, I'm currently working on other projects but if you have anything you might want to discuss I'll be glad to help !
